version: "3.0"

services:
  hacknu-api:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - hacknu-local-version

networks:
  hacknu-local-version:
    external: true